config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :administrators
  resources :neighbors
  resources :machines
  resources :historicals
  resources :type_users
  resources :users
  resources :residentials
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/historical.rb
class Historical < ApplicationRecord
  belongs_to :user
end

app/controllers/historicals_controller.rb
class HistoricalsController < ApplicationController
  before_action :set_historical, only: [:show, :edit, :update, :destroy]

  # GET /historicals
  # GET /historicals.json
  def index
    @historicals = Historical.all
  end

  # GET /historicals/1
  # GET /historicals/1.json
  def show
  end

  # GET /historicals/new
  def new
    @historical = Historical.new
  end

  # GET /historicals/1/edit
  def edit
  end

  # POST /historicals
  # POST /historicals.json
  def create
    @historical = Historical.new(historical_params)

    respond_to do |format|
      if @historical.save
        format.html { redirect_to @historical, notice: 'Historical was successfully created.' }
        format.json { render :show, status: :created, location: @historical }
      else
        format.html { render :new }
        format.json { render json: @historical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historicals/1
  # PATCH/PUT /historicals/1.json
  def update
    respond_to do |format|
      if @historical.update(historical_params)
        format.html { redirect_to @historical, notice: 'Historical was successfully updated.' }
        format.json { render :show, status: :ok, location: @historical }
      else
        format.html { render :edit }
        format.json { render json: @historical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historicals/1
  # DELETE /historicals/1.json
  def destroy
    @historical.destroy
    respond_to do |format|
      format.html { redirect_to historicals_url, notice: 'Historical was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_historical
      @historical = Historical.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def historical_params
      params.require(:historical).permit(:id_user, :collection, :month, :administration_value, :discount, :user_id)
    end
end

app/helpers/historicals_helper.rb
module HistoricalsHelper
end

app/views/historicals/_form.html.erb
<%= form_with(model: historical, local: true) do |form| %>
  <% if historical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(historical.errors.count, "error") %> prohibited this historical from being saved:</h2>

      <ul>
      <% historical.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_user %>
    <%= form.text_field :id_user, id: :historical_id_user %>
  </div>

  <div class="field">
    <%= form.label :collection %>
    <%= form.text_field :collection, id: :historical_collection %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.date_select :month, id: :historical_month %>
  </div>

  <div class="field">
    <%= form.label :administration_value %>
    <%= form.text_field :administration_value, id: :historical_administration_value %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount, id: :historical_discount %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :historical_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/historicals/edit.html.erb
<h1>Editing Historical</h1>

<%= render 'form', historical: @historical %>

<%= link_to 'Show', @historical %> |
<%= link_to 'Back', historicals_path %>

app/views/historicals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Historicals</h1>

<table>
  <thead>
    <tr>
      <th>Id user</th>
      <th>Collection</th>
      <th>Month</th>
      <th>Administration value</th>
      <th>Discount</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @historicals.each do |historical| %>
      <tr>
        <td><%= historical.id_user %></td>
        <td><%= historical.collection %></td>
        <td><%= historical.month %></td>
        <td><%= historical.administration_value %></td>
        <td><%= historical.discount %></td>
        <td><%= historical.user %></td>
        <td><%= link_to 'Show', historical %></td>
        <td><%= link_to 'Edit', edit_historical_path(historical) %></td>
        <td><%= link_to 'Destroy', historical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Historical', new_historical_path %>

app/views/historicals/new.html.erb
<h1>New Historical</h1>

<%= render 'form', historical: @historical %>

<%= link_to 'Back', historicals_path %>

app/views/historicals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id user:</strong>
  <%= @historical.id_user %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @historical.collection %>
</p>

<p>
  <strong>Month:</strong>
  <%= @historical.month %>
</p>

<p>
  <strong>Administration value:</strong>
  <%= @historical.administration_value %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @historical.discount %>
</p>

<p>
  <strong>User:</strong>
  <%= @historical.user %>
</p>

<%= link_to 'Edit', edit_historical_path(@historical) %> |
<%= link_to 'Back', historicals_path %>