config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :administrators
  resources :neighbors
  resources :machines
  resources :historicals
  resources :type_users
  resources :users
  resources :residentials
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/neighbor.rb
class Neighbor < ApplicationRecord
  belongs_to :residential
end

app/controllers/neighbors_controller.rb
class NeighborsController < ApplicationController
  before_action :set_neighbor, only: [:show, :edit, :update, :destroy]

  # GET /neighbors
  # GET /neighbors.json
  def index
    @neighbors = Neighbor.all
  end

  # GET /neighbors/1
  # GET /neighbors/1.json
  def show
  end

  # GET /neighbors/new
  def new
    @neighbor = Neighbor.new
  end

  # GET /neighbors/1/edit
  def edit
  end

  # POST /neighbors
  # POST /neighbors.json
  def create
    @neighbor = Neighbor.new(neighbor_params)

    respond_to do |format|
      if @neighbor.save
        format.html { redirect_to @neighbor, notice: 'Neighbor was successfully created.' }
        format.json { render :show, status: :created, location: @neighbor }
      else
        format.html { render :new }
        format.json { render json: @neighbor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighbors/1
  # PATCH/PUT /neighbors/1.json
  def update
    respond_to do |format|
      if @neighbor.update(neighbor_params)
        format.html { redirect_to @neighbor, notice: 'Neighbor was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighbor }
      else
        format.html { render :edit }
        format.json { render json: @neighbor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighbors/1
  # DELETE /neighbors/1.json
  def destroy
    @neighbor.destroy
    respond_to do |format|
      format.html { redirect_to neighbors_url, notice: 'Neighbor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighbor
      @neighbor = Neighbor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighbor_params
      params.require(:neighbor).permit(:name, :location, :residential_id)
    end
end

app/helpers/neighbors_helper.rb
module NeighborsHelper
end

app/views/neighbors/_form.html.erb
<%= form_with(model: neighbor, local: true) do |form| %>
  <% if neighbor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(neighbor.errors.count, "error") %> prohibited this neighbor from being saved:</h2>

      <ul>
      <% neighbor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :neighbor_name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :neighbor_location %>
  </div>

  <div class="field">
    <%= form.label :residential_id %>
    <%= form.text_field :residential_id, id: :neighbor_residential_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/neighbors/edit.html.erb
<h1>Editing Neighbor</h1>

<%= render 'form', neighbor: @neighbor %>

<%= link_to 'Show', @neighbor %> |
<%= link_to 'Back', neighbors_path %>

app/views/neighbors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Neighbors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Residential</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @neighbors.each do |neighbor| %>
      <tr>
        <td><%= neighbor.name %></td>
        <td><%= neighbor.location %></td>
        <td><%= neighbor.residential %></td>
        <td><%= link_to 'Show', neighbor %></td>
        <td><%= link_to 'Edit', edit_neighbor_path(neighbor) %></td>
        <td><%= link_to 'Destroy', neighbor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neighbor', new_neighbor_path %>

app/views/neighbors/new.html.erb
<h1>New Neighbor</h1>

<%= render 'form', neighbor: @neighbor %>

<%= link_to 'Back', neighbors_path %>

app/views/neighbors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @neighbor.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @neighbor.location %>
</p>

<p>
  <strong>Residential:</strong>
  <%= @neighbor.residential %>
</p>

<%= link_to 'Edit', edit_neighbor_path(@neighbor) %> |
<%= link_to 'Back', neighbors_path %>