config/routes.rb
Rails.application.routes.draw do
  resources :cities
  resources :administrators
  resources :neighbors
  resources :machines
  resources :historicals
  resources :type_users
  resources :users
  resources :residentials
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :historical
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  # GET /machines
  # GET /machines.json
  def index
    @machines = Machine.all
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
  end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1
  # PATCH/PUT /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_machine
      @machine = Machine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def machine_params
      params.require(:machine).permit(:accumulated, :inserted, :id_user, :month, :historical_id)
    end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_with(model: machine, local: true) do |form| %>
  <% if machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :accumulated %>
    <%= form.text_field :accumulated, id: :machine_accumulated %>
  </div>

  <div class="field">
    <%= form.label :inserted %>
    <%= form.number_field :inserted, id: :machine_inserted %>
  </div>

  <div class="field">
    <%= form.label :id_user %>
    <%= form.text_field :id_user, id: :machine_id_user %>
  </div>

  <div class="field">
    <%= form.label :month %>
    <%= form.date_select :month, id: :machine_month %>
  </div>

  <div class="field">
    <%= form.label :historical_id %>
    <%= form.text_field :historical_id, id: :machine_historical_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/machines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Machines</h1>

<table>
  <thead>
    <tr>
      <th>Accumulated</th>
      <th>Inserted</th>
      <th>Id user</th>
      <th>Month</th>
      <th>Historical</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.accumulated %></td>
        <td><%= machine.inserted %></td>
        <td><%= machine.id_user %></td>
        <td><%= machine.month %></td>
        <td><%= machine.historical %></td>
        <td><%= link_to 'Show', machine %></td>
        <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
        <td><%= link_to 'Destroy', machine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Machine', new_machine_path %>

app/views/machines/new.html.erb
<h1>New Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Back', machines_path %>

app/views/machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accumulated:</strong>
  <%= @machine.accumulated %>
</p>

<p>
  <strong>Inserted:</strong>
  <%= @machine.inserted %>
</p>

<p>
  <strong>Id user:</strong>
  <%= @machine.id_user %>
</p>

<p>
  <strong>Month:</strong>
  <%= @machine.month %>
</p>

<p>
  <strong>Historical:</strong>
  <%= @machine.historical %>
</p>

<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>